// <auto-generated />
using System;
using AudioAtlasInfrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioAtlas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728141151_AddUniqueIndexToCountryIsoCode")]
    partial class AddUniqueIndexToCountryIsoCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioAtlasDomain.Genres.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastEditedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlaylistLink")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SensitiveDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedById");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LastEditedById");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreAlias", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenreId", "Alias");

                    b.ToTable("GenreAliases");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreSource", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceLink")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GenreId", "SourceLink");

                    b.ToTable("GenreSources");
                });

            modelBuilder.Entity("AudioAtlasDomain.Geography.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isoCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("isoCode")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("AudioAtlasDomain.MusicMetadata.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("AudioAtlasDomain.Search.SearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextContinent")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContextRegion")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ResultCount")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SearchQueries", (string)null);
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.RejectedSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("SubmissionId");

                    b.ToTable("RejectedSubmissions");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.RejectionReason", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("GuidelineRef")
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("RejectionReasons", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "origin_misattribution",
                            GuidelineRef = "respect-cultural-origins",
                            IsActive = true,
                            Label = "Origin incorrectly credited",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "terminology_issue",
                            GuidelineRef = "appropriate-terminology",
                            IsActive = true,
                            Label = "Inappropriate or incorrect naming/terms",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "unverifiable_speculative",
                            GuidelineRef = "do-not-speculate",
                            IsActive = true,
                            Label = "Speculative claim, not supportable",
                            SortOrder = 3
                        },
                        new
                        {
                            Code = "insufficient_sources",
                            GuidelineRef = "cite-sources",
                            IsActive = true,
                            Label = "Missing or inadequate citations",
                            SortOrder = 4
                        },
                        new
                        {
                            Code = "inaccurate_content",
                            GuidelineRef = "accuracy",
                            IsActive = true,
                            Label = "Factually incorrect history/context",
                            SortOrder = 5
                        },
                        new
                        {
                            Code = "incomplete_required_fields",
                            GuidelineRef = "genre-data-requirements",
                            IsActive = true,
                            Label = "Missing required data fields",
                            SortOrder = 6
                        },
                        new
                        {
                            Code = "duplicate",
                            GuidelineRef = "data-integrity",
                            IsActive = true,
                            Label = "Already exists in the atlas",
                            SortOrder = 7
                        },
                        new
                        {
                            Code = "out_of_scope",
                            GuidelineRef = "scope",
                            IsActive = true,
                            Label = "Not a music genre / not notable",
                            SortOrder = 8
                        },
                        new
                        {
                            Code = "copyright_violation",
                            GuidelineRef = "licensing-copyright",
                            IsActive = true,
                            Label = "Copied or unlicensable content",
                            SortOrder = 9
                        },
                        new
                        {
                            Code = "spam_or_abuse",
                            GuidelineRef = "code-of-conduct",
                            IsActive = true,
                            Label = "Spam, vandalism, or CoC breach",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("NewGenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReasonCode")
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SensitiveDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("TargetGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RejectionReasonCode");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("TargetGenreId");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionAlias", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubmissionId", "Alias");

                    b.ToTable("SubmissionAliases");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionSource", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceLink")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubmissionId", "SourceLink");

                    b.ToTable("SubmissionSources");
                });

            modelBuilder.Entity("AudioAtlasDomain.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedContributionGuidelinesAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcceptedContributionGuidelinesVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("AcceptedPrivacyPolicyAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcceptedPrivacyPolicyVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedPlaceholder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemUser")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AudioAtlasDomain.Users.PendingExternalRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SuggestedUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LoginProvider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("PendingExternalRegistrations", (string)null);
                });

            modelBuilder.Entity("AudioAtlasDomain.Users.RoleChangeAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PreviousRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("ChangedById");

                    b.HasIndex("TargetUserId");

                    b.ToTable("RoleChangeAuditLogs", (string)null);
                });

            modelBuilder.Entity("FavoriteGenre", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("FavoriteGenre");
                });

            modelBuilder.Entity("GenreCountry", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("GenreCountry");
                });

            modelBuilder.Entity("GenreHierarchy", b =>
                {
                    b.Property<Guid>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ParentGenreId", "SubGenreId");

                    b.HasIndex("SubGenreId");

                    b.ToTable("GenreHierarchy");
                });

            modelBuilder.Entity("GenreInstrument", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("GenreInstrument");
                });

            modelBuilder.Entity("GenreSimilarity", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SimilarGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "SimilarGenreId");

                    b.HasIndex("SimilarGenreId");

                    b.ToTable("GenreSimilarity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SubmissionCountry", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("SubmissionCountry");
                });

            modelBuilder.Entity("SubmissionInstrument", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("SubmissionInstrument");
                });

            modelBuilder.Entity("SubmissionPredecessorGenre", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SubmissionPredecessorGenre");
                });

            modelBuilder.Entity("SubmissionSimilarGenre", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SubmissionSimilarGenre");
                });

            modelBuilder.Entity("SubmissionSubGenre", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubmissionId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("SubmissionSubGenre");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.Genre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "ArchivedBy")
                        .WithMany()
                        .HasForeignKey("ArchivedById");

                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "LastEditedBy")
                        .WithMany()
                        .HasForeignKey("LastEditedById");

                    b.Navigation("ArchivedBy");

                    b.Navigation("Author");

                    b.Navigation("LastEditedBy");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreAlias", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", "Genre")
                        .WithMany("Aliases")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreSource", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", "Genre")
                        .WithMany("Sources")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.RejectedSubmission", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", "Submission")
                        .WithOne("RejectedSubmission")
                        .HasForeignKey("AudioAtlasDomain.Submissions.RejectedSubmission", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.Submission", b =>
                {
                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.RejectionReason", "RejectionReason")
                        .WithMany()
                        .HasForeignKey("RejectionReasonCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AudioAtlasDomain.Genres.Genre", "TargetGenre")
                        .WithMany()
                        .HasForeignKey("TargetGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("RejectionReason");

                    b.Navigation("ReviewedBy");

                    b.Navigation("TargetGenre");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionAlias", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", "Submission")
                        .WithMany("Aliases")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionSource", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", "Submission")
                        .WithMany("Sources")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AudioAtlasDomain.Users.RoleChangeAuditLog", b =>
                {
                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("FavoriteGenre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreCountry", b =>
                {
                    b.HasOne("AudioAtlasDomain.Geography.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreHierarchy", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("SubGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreInstrument", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.MusicMetadata.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreSimilarity", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("SimilarGenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AudioAtlasDomain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionCountry", b =>
                {
                    b.HasOne("AudioAtlasDomain.Geography.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionInstrument", b =>
                {
                    b.HasOne("AudioAtlasDomain.MusicMetadata.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionPredecessorGenre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionSimilarGenre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionSubGenre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.Genre", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.Submission", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("RejectedSubmission");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
