// <auto-generated />
using System;
using AudioAtlasInfrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioAtlasInfrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioAtlasDomain.Genres.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlaylistLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SensitiveDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreAliases");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreSources");
                });

            modelBuilder.Entity("AudioAtlasDomain.Geography.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("AudioAtlasDomain.MusicMetadata.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.RejectedSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("SubmissionId");

                    b.ToTable("RejectedSubmissions");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ExistingGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("NewGenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionAliases");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionSources");
                });

            modelBuilder.Entity("AudioAtlasDomain.Users.FavoriteGenre", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("FavoriteGenres");
                });

            modelBuilder.Entity("CountryGenre", b =>
                {
                    b.Property<Guid>("CountriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CountriesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("CountryGenre");
                });

            modelBuilder.Entity("GenreInstrument", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenresId", "InstrumentsId");

                    b.HasIndex("InstrumentsId");

                    b.ToTable("GenreInstrument");
                });

            modelBuilder.Entity("SubmissionPredecessorGenres", b =>
                {
                    b.Property<Guid>("PredecessorGenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Submission2Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PredecessorGenresId", "Submission2Id");

                    b.HasIndex("Submission2Id");

                    b.ToTable("SubmissionPredecessorGenres");
                });

            modelBuilder.Entity("SubmissionSimilarGenres", b =>
                {
                    b.Property<Guid>("SimilarGenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SimilarGenresId", "SubmissionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionSimilarGenres");
                });

            modelBuilder.Entity("SubmissionSubGenres", b =>
                {
                    b.Property<Guid>("SubGenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Submission1Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubGenresId", "Submission1Id");

                    b.HasIndex("Submission1Id");

                    b.ToTable("SubmissionSubGenres");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreAlias", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", "Genre")
                        .WithMany("Aliases")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.GenreSource", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", "Genre")
                        .WithMany("Sources")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AudioAtlasDomain.Geography.Country", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany("Countries")
                        .HasForeignKey("SubmissionId");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.RejectedSubmission", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", "Submission")
                        .WithOne("RejectedSubmission")
                        .HasForeignKey("AudioAtlasDomain.Submissions.RejectedSubmission", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionAlias", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", "Submission")
                        .WithMany("Aliases")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.SubmissionSource", b =>
                {
                    b.HasOne("AudioAtlasDomain.Submissions.Submission", "Submission")
                        .WithMany("Sources")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AudioAtlasDomain.Users.FavoriteGenre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CountryGenre", b =>
                {
                    b.HasOne("AudioAtlasDomain.Geography.Country", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreInstrument", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.MusicMetadata.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionPredecessorGenres", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("PredecessorGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("Submission2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionSimilarGenres", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("SimilarGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionSubGenres", b =>
                {
                    b.HasOne("AudioAtlasDomain.Genres.Genre", null)
                        .WithMany()
                        .HasForeignKey("SubGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioAtlasDomain.Submissions.Submission", null)
                        .WithMany()
                        .HasForeignKey("Submission1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AudioAtlasDomain.Genres.Genre", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AudioAtlasDomain.Submissions.Submission", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Countries");

                    b.Navigation("RejectedSubmission");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
