name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - "Backend/**"

  push:
    branches:
      - main
    paths:
      - "Backend/**"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: 'Backend/**/packages.lock.json'


      - name: Restore dependencies
        working-directory: ./Backend
        run: dotnet restore

      - name: Build backend
        working-directory: ./Backend
        run: dotnet build --configuration Release --no-restore

      - name: Publish backend
        working-directory: ./Backend
        run: dotnet publish -c Release -o publish --no-build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: Backend/publish


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: 'Backend/**/packages.lock.json'

      - name: Restore dependencies
        working-directory: ./Backend
        run: dotnet restore

      - name: Run backend tests
        working-directory: ./Backend
        run: dotnet test --configuration Release --no-build


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3425963DFCB43CC855F2968ACFCF63F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B65326FD3F94047AF49E32DB65CCC9A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2D4CD78EF294700891063B3F237FB7C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: api-audioatlas
          slot-name: Production
          package: backend-artifact